version: "3"

services:
  merel:
    container_name: merel
    image: merel:local
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - "3003:3000"
    networks:
      - merel-network
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -c "npm i && npm run start:dev"
    env_file:
      - ./docker/.env
  mongo:
    container_name: mongo
    image: mongo:4.4.6
    restart: always
    ports:
      - 27017:27017
    networks:
      - merel-network
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: merel
      DB_NAME: merel
      DB_USER: root
      DB_PASSWORD: root

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    depends_on:
      - mongo
    networks:
      - merel-network
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/

networks:
  merel-network:
    external: true
